version: "3.9"

services:
    static1:
        image: nginx
        ports:
            - "3005:80"
        volumes:
            - ./Static_HTTP_server/www:/usr/share/nginx/html
    static2:
        image: nginx
        ports:
            - "3006:80"
        volumes:
            - ./Static_HTTP_server/www:/usr/share/nginx/html
    dynamic1:
        build: ./expressJs
        image: dynamic_server:latest
        ports:
            - "3007:3006"
        environment:
          - NO_SERVER=1
    dynamic2:
        build: ./expressJs
        image: dynamic_server:latest
        ports:
            - "3008:3006"
        environment:
          - NO_SERVER=2
    reverseProxy:
        build: ./reverse_proxy
        image: reverse_proxy:latest
        ports:
            - "8081:80"
